@startuml
'Green is a struct'

hide empty members

class DialogueManager<<M, yellow>>{
    +ui : canvas 
    +isRunning : bool
    -name : TextMeshPro
    -text : TextMeshPro
    -portrait : Image
    -backgroundView : Image
    -textBackground : Image
    +Event action<string> ChoiceMade
    +void StartDialogue(Dialogue dialogueToSet)
    +void StopDialogue()
    -void ShowButton()
    -void PressButton()
    -void NextDialoguePiece()
    -void Skip()
    -void PlayLetterSound()
    -void PlaySound()
    -void PlayBackgroundSound()
}

Abstract DialogueEncounter{
    +dialogues : list<Dialogue>
    #void SendDialogue()
    -Event action<> SomethingHappens
    -void StartEvent()
}

class Dialogue<<S, red>>{
    +pieces : DialoguePiece[]
    +choices : list<Choice>
    +mode : Mode
}

class Actor<<S, red>>{
    +name : string
    +reaction : dictionary<Reaction,Sprite>
}

class DialoguePiece<<S, red>>{
    +actor : Actor
    +reactions : Reaction
    +text : string
    +soundForLetter : Sound
    +sound : Sound
    +backgroundSound : Sound
    +speed : float
}

class Mode<<S, red>>{
    +Instant
    +TypeOut
}

Class Choice<<S, green>>{
    +choiceName : list<string>
    +dialogue : Dialogue
    
}

Class Reaction<<S, red>>{
    Neutral
    Happy
    Sad    
    Angry
}

Dialogue *-- DialoguePiece
DialoguePiece - Actor
Dialogue - Mode
DialogueManager o-- DialogueEncounter
DialogueEncounter o-- Dialogue
Dialogue -- Choice
DialoguePiece -- Reaction
Actor -- Reaction

@enduml